language: node_js
node_js:
  - 4
env:
  - CXX=g++-4.8
install:
  - npm install gulp bower -g
  - npm install
  - bower update
script:
  - gulp make
  - gulp example
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
- >-
  test $TRAVIS_TAG &&
  node_modules/.bin/psc-publish > .pursuit.json &&
  curl -X POST http://pursuit.purescript.org/packages \
    -d @.pursuit.json \
    -H 'Accept: application/json' \
    -H "Authorization: token ${GITHUB_TOKEN}"
